# Generated by Django 5.2.1 on 2025-07-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bridges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bridge",
            name="bridge_type",
            field=models.CharField(
                choices=[
                    ("beam", "Cầu dầm"),
                    ("arch", "Cầu vòm"),
                    ("suspension", "Cầu treo"),
                    ("cable_stayed", "Cầu dây văng"),
                    ("other", "Khác"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bridge",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bridge",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="bridge",
            name="length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bridge",
            name="material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bridge",
            name="width",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
